# db config
spring:
  mvc:
   static-path-pattern: /static/**
  datasource:
   driver-class-name: org.mariadb.jdbc.Driver
   url: jdbc:mariadb://localhost:3306/board33
   username: root
   password: green502


#mybatis config
mybatis:
 type-aliases-package: com.green.board8
 mapper-locations : mapper/**/*.xml


#swagger
springdoc:
 swagger-ui:
  path: /swagger.html